services:
  fastapi-app:
    build:
      context: fastapi-app
      dockerfile: dev.Dockerfile
    ports:
      - ${FASTAPI_APP_PORT}:8000
    init: true
    stop_grace_period: 60s
    volumes:
      - ./fastapi-app/app.py:/app/app.py
      - ./fastapi-app/api:/app/api
      - ./fastapi-app/public:/app/public
      - ./fastapi-app/utils:/app/utils
      - students_images:/app/students_images
      - vectors:/app/vectors
    environment:
      MONGO_URL: ${MONGODB_URL}
      USER_TOKEN_SECRET_KEY: ${FASTAPI_APP_USER_TOKEN_SECRET_KEY}
      JWT_RECOGNIZE_SECRET_KEY: ${FASTAPI_APP_JWT_RECOGNIZE_SECRET_KEY}
      JWT_ALGORITHM: ${FASTAPI_APP_JWT_ALGORITHM}
      OAUTH_GOOGLE_CLIENT_ID: ${FASTAPI_APP_OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${FASTAPI_APP_OAUTH_GOOGLE_CLIENT_SECRET}
      OAUTH_GOOGLE_STATE_SECRET: ${FASTAPI_APP_OAUTH_GOOGLE_STATE_SECRET}
      OAUTH_URL_REDIRECT_AFTER_LOGIN: ${FASTAPI_APP_OAUTH_URL_REDIRECT_AFTER_LOGIN}
      FRONT_APP_EXTERNAL_URL: ${FRONT_APP_URL}
      GMT_TIMEZONE: ${FASTAPI_APP_GMT_TIMEZONE}
    depends_on:
      - mongo
      - deepface

  front-app:
    build:
      context: front-app
      dockerfile: dev.Dockerfile
    ports:
      - ${FRONT_APP_PORT}:5173
    environment:
      VITE_FASTAPI_APP_URL: ${FASTAPI_APP_URL}
      VITE_FASTAPI_APP_URL_WS: ${FASTAPI_APP_URL_WS}
    volumes:
      - ./front-app/imgs:/app/imgs
      - ./front-app/public:/app/public
      - ./front-app/src:/app/src
      - ./front-app/components.json:/app/components.json
      - ./front-app/eslint.config.js:/app/eslint.config.js
      - ./front-app/index.html:/app/index.html
      - ./front-app/orval.config.ts:/app/orval.config.ts
      - ./front-app/postcss.config.js/:/app/postcss.config.js
      - ./front-app/schemas.json:/app/schemas.json
      - ./front-app/tailwind.config.js:/app/tailwind.config.js
      - ./front-app/tsconfig.app.json:/app/tsconfig.app.json
      - ./front-app/tsconfig.json:/app/tsconfig.json
      - ./front-app/tsconfig.node.json:/app/tsconfig.node.json
      - ./front-app/vite.config.ts:/app/vite.config.ts
    depends_on:
      - fastapi-app

  deepface:
    image: serengil/deepface
    volumes:
      - students_images:/public/students_images

  mongo:
    image: mongo:8.0.4
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo_data:

  students_images:

  vectors:
