services:
  fastapi-app:
    build:
      context: fastapi-app
      dockerfile: dev.Dockerfile
    ports:
      - ${FASTAPI_APP_PORT}:8000
    volumes:
      - ./fastapi-app/app.py:/app/app.py
      - ./fastapi-app/api:/app/api
      - ./fastapi-app/public:/app/public
      - ./fastapi-app/utils:/app/utils
      - students_images:/app/students_images
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
      - MONGO_DB=fastapi_db
    depends_on:
      - mongo

  front-app:
    build:
      context: front-app
      dockerfile: dev.Dockerfile
    ports:
      - ${FRONT_APP_PORT}:5173
    environment:
      - VITE_FASTAPI_APP_URL=${FASTAPI_APP_URL}
    volumes:
      - ./front-app/imgs:/app/imgs
      - ./front-app/public:/app/public
      - ./front-app/src:/app/src
      - ./front-app/components.json:/app/components.json
      - ./front-app/eslint.config.js:/app/eslint.config.js
      - ./front-app/index.html:/app/index.html
      - ./front-app/postcss.config.js/:/app/postcss.config.js
      - ./front-app/tailwind.config.js:/app/tailwind.config.js
      - ./front-app/tsconfig.app.json:/app/tsconfig.app.json
      - ./front-app/tsconfig.json:/app/tsconfig.json
      - ./front-app/tsconfig.node.json:/app/tsconfig.node.json
      - ./front-app/vite.config.ts:/app/vite.config.ts
    depends_on:
      - fastapi-app

  deepface:
    image: serengil/deepface
    volumes:
      - students_images:/public/students_images

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH: false



volumes:
  mongo_data:

  students_images:
