/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Get Active Tokens
 */
export const getActiveTokensApiRollcallActiveTokensGetResponseItem = zod.string()
export const getActiveTokensApiRollcallActiveTokensGetResponse = zod.array(getActiveTokensApiRollcallActiveTokensGetResponseItem)

/**
 * @summary Start Rollcall
 */
export const startRollcallApiRollcallStartPostResponse = zod.any()

/**
 * @summary Stop Rollcall
 */
export const stopRollcallApiRollcallStopPostResponse = zod.any()

