/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Get Attendances Dates
 */
export const getAttendancesDatesApiAttendancesAttendanceDatesGetResponse = zod.any()

/**
 * @summary Create Attendance
 */
export const createAttendanceApiAttendancesPostResponse = zod.object({
  "date": zod.string().date(),
  "times": zod.array(zod.string()),
  "ra": zod.number()
})

/**
 * @summary Create Attendance Csv By Date
 */
export const createAttendanceCsvByDateApiAttendancesCsvPostResponse = zod.any()

