/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Get Student Image
 */
export const getStudentImageApiStaticStudentsImagesStudentRaGetParams = zod.object({
  "student_ra": zod.number()
})

export const getStudentImageApiStaticStudentsImagesStudentRaGetResponse = zod.any()

