/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Get All Students
 */
export const getAllStudentsApiStudentsGetResponse = zod.any()

/**
 * @summary Get Student By Ra
 */
export const getStudentByRaApiStudentsStudentRaGetParams = zod.object({
  "student_ra": zod.number()
})

export const getStudentByRaApiStudentsStudentRaGetResponse = zod.any()

/**
 * @summary Update Student By Ra
 */
export const updateStudentByRaApiStudentsStudentRaPatchParams = zod.object({
  "student_ra": zod.number()
})

export const updateStudentByRaApiStudentsStudentRaPatchResponse = zod.any()

