/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Get All Students
 */
export const getAllStudentsApiStudentsGetResponseItem = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})
export const getAllStudentsApiStudentsGetResponse = zod.array(getAllStudentsApiStudentsGetResponseItem)

/**
 * @summary Get Student By Ra
 */
export const getStudentByRaApiStudentsStudentRaGetParams = zod.object({
  "student_ra": zod.number()
})

export const getStudentByRaApiStudentsStudentRaGetResponse = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})

/**
 * @summary Update Student By Ra
 */
export const updateStudentByRaApiStudentsStudentRaPatchParams = zod.object({
  "student_ra": zod.number()
})

export const updateStudentByRaApiStudentsStudentRaPatchResponse = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})

