/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Get Students
 */
export const getStudentsApiStudentsGetQueryParams = zod.object({
  "active": zod.boolean().optional()
})

export const getStudentsApiStudentsGetResponseItem = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})
export const getStudentsApiStudentsGetResponse = zod.array(getStudentsApiStudentsGetResponseItem)

/**
 * @summary Get All Students
 */
export const getAllStudentsApiStudentsAllGetResponseItem = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})
export const getAllStudentsApiStudentsAllGetResponse = zod.array(getAllStudentsApiStudentsAllGetResponseItem)

/**
 * @summary Get Student By Ra
 */
export const getStudentByRaApiStudentsStudentRaGetParams = zod.object({
  "student_ra": zod.number()
})

export const getStudentByRaApiStudentsStudentRaGetResponse = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})

/**
 * @summary Update Student By Ra
 */
export const updateStudentByRaApiStudentsStudentRaPatchParams = zod.object({
  "student_ra": zod.number()
})

export const updateStudentByRaApiStudentsStudentRaPatchResponse = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})

/**
 * @summary Activate Student Bulk By Ra
 */
export const activateStudentBulkByRaApiStudentsBulkActivatePatchBodyItem = zod.number()
export const activateStudentBulkByRaApiStudentsBulkActivatePatchBody = zod.array(activateStudentBulkByRaApiStudentsBulkActivatePatchBodyItem)

export const activateStudentBulkByRaApiStudentsBulkActivatePatchResponseItem = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})
export const activateStudentBulkByRaApiStudentsBulkActivatePatchResponse = zod.array(activateStudentBulkByRaApiStudentsBulkActivatePatchResponseItem)

/**
 * @summary Deactivate Student Bulk By Ra
 */
export const deactivateStudentBulkByRaApiStudentsBulkDeactivatePatchBodyItem = zod.number()
export const deactivateStudentBulkByRaApiStudentsBulkDeactivatePatchBody = zod.array(deactivateStudentBulkByRaApiStudentsBulkDeactivatePatchBodyItem)

export const deactivateStudentBulkByRaApiStudentsBulkDeactivatePatchResponseItem = zod.object({
  "_id": zod.string().or(zod.null()).optional(),
  "name": zod.string(),
  "ra": zod.number(),
  "active": zod.boolean().optional(),
  "image_path": zod.string().or(zod.null())
})
export const deactivateStudentBulkByRaApiStudentsBulkDeactivatePatchResponse = zod.array(deactivateStudentBulkByRaApiStudentsBulkDeactivatePatchResponseItem)

