/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Recognize
 */
export const recognizeApiFacialRecognitionRecognizePostResponse = zod.any()

/**
 * @summary Represent Face
 */
export const representFaceApiFacialRecognitionRepresentPostBody = zod.object({
  "img_path": zod.string(),
  "model_name": zod.string().optional()
})

export const representFaceApiFacialRecognitionRepresentPostResponse = zod.any()

/**
 * @summary Verify Face
 */
export const verifyFaceApiFacialRecognitionVerifyPostBody = zod.object({
  "img1_path": zod.string(),
  "enforce_detection": zod.boolean().optional(),
  "model_name": zod.string().optional(),
  "align": zod.boolean().optional()
})

export const verifyFaceApiFacialRecognitionVerifyPostResponse = zod.any()

