/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Recognize
 */
export const recognizeApiFacialRecognitionRecognizePostResponse = zod.object({
  "verified": zod.boolean(),
  "students": zod.array(zod.object({
  "name": zod.string(),
  "ra": zod.number(),
  "token": zod.string()
})).optional()
})

