/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BodyRecognizeApiFacialRecognitionRecognizePost {
  image_base64: string;
  recognize_token: string;
}
