/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyAuthJwtLoginAuthLoginPostClientId } from './bodyAuthJwtLoginAuthLoginPostClientId';
import type { BodyAuthJwtLoginAuthLoginPostClientSecret } from './bodyAuthJwtLoginAuthLoginPostClientSecret';
import type { BodyAuthJwtLoginAuthLoginPostGrantType } from './bodyAuthJwtLoginAuthLoginPostGrantType';

export interface BodyAuthJwtLoginAuthLoginPost {
  client_id?: BodyAuthJwtLoginAuthLoginPostClientId;
  client_secret?: BodyAuthJwtLoginAuthLoginPostClientSecret;
  grant_type?: BodyAuthJwtLoginAuthLoginPostGrantType;
  password: string;
  scope?: string;
  username: string;
}
