/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyAuthJwtLoginApiAuthLoginPostClientId } from './bodyAuthJwtLoginApiAuthLoginPostClientId';
import type { BodyAuthJwtLoginApiAuthLoginPostClientSecret } from './bodyAuthJwtLoginApiAuthLoginPostClientSecret';
import type { BodyAuthJwtLoginApiAuthLoginPostGrantType } from './bodyAuthJwtLoginApiAuthLoginPostGrantType';

export interface BodyAuthJwtLoginApiAuthLoginPost {
  client_id?: BodyAuthJwtLoginApiAuthLoginPostClientId;
  client_secret?: BodyAuthJwtLoginApiAuthLoginPostClientSecret;
  grant_type?: BodyAuthJwtLoginApiAuthLoginPostGrantType;
  password: string;
  scope?: string;
  username: string;
}
