/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyUpdateStudentByRaApiStudentsStudentRaPatchActive } from './bodyUpdateStudentByRaApiStudentsStudentRaPatchActive';
import type { BodyUpdateStudentByRaApiStudentsStudentRaPatchImageBase64 } from './bodyUpdateStudentByRaApiStudentsStudentRaPatchImageBase64';
import type { BodyUpdateStudentByRaApiStudentsStudentRaPatchName } from './bodyUpdateStudentByRaApiStudentsStudentRaPatchName';
import type { BodyUpdateStudentByRaApiStudentsStudentRaPatchRa } from './bodyUpdateStudentByRaApiStudentsStudentRaPatchRa';

export interface BodyUpdateStudentByRaApiStudentsStudentRaPatch {
  active?: BodyUpdateStudentByRaApiStudentsStudentRaPatchActive;
  image_base64?: BodyUpdateStudentByRaApiStudentsStudentRaPatchImageBase64;
  name?: BodyUpdateStudentByRaApiStudentsStudentRaPatchName;
  ra?: BodyUpdateStudentByRaApiStudentsStudentRaPatchRa;
}
