/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BodyCreateStudentApiStudentsPost {
  image_base64: string;
  name: string;
  ra: number;
}
