/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface DeepFaceVerifyRequest {
  align?: boolean;
  enforce_detection?: boolean;
  img1_path: string;
  model_name?: string;
}
