/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type OauthGoogleJwtCallbackApiAuthGoogleCallbackGetParams = {
code?: string | null;
code_verifier?: string | null;
state?: string | null;
error?: string | null;
};
