/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { _StudentId } from './_studentId';
import type { StudentImagePath } from './studentImagePath';

export interface Student {
  /** MongoDB document ObjectID */
  _id?: _StudentId;
  active?: boolean;
  image_path: StudentImagePath;
  name: string;
  ra: number;
}
